### ISSUE TITLE
Concern about Lesson Objectives

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#13]
When I got to reviewing the exercises episode it made me wonder if they will have objectives that are specific enough.  While we talk about SMART objectives, sometimes when creating objectives we create objectives that are for the whole lesson (and therefore not very specific) and then those that are for a particular episode (and are much more specific).  In the objectives episode they are thinking about the whole lesson.  Maybe we should have them also break down one of the lesson objectives into several specific episode objectives?

Or we could provide some guidance in the objectives episode that if find that their objectives are broad, to think about a subsection of the lesson using one of their broad objectives and split that into several specific objectives.

**Comment by tobyhodges** [comment]
You're right, I've made the assumption here that episode-level objectives will exist, but their creation has slipped through the cracks so far...

I think it will make most sense as an exercise at the end of the Carpentries Workbench episode. Here, they are creating new episodes anyway, and we can guide them in thinking about how to choose what episode to create (decomposing the lesson into smaller chunks), then give them time to consider what the objectives would be within one of those chunks.

I think this is quite a big block that is missing, to be honest: it's an exercise (or two) that could take a fair bit of time because collaborators will need to discuss the breakdown into episodes together, before they individually take on an episode and start planning objectives for it. We should probably give them time after that to discuss again as a group, to ensure that the planned episodes will flow together without gaps or significant overlap.

This will need discussing at our next coworking session!

**Comment by tobyhodges** [comment]
Closing this now that it has been superseded by some more specific issues (e.g. #73) and since an episode was added to work on this.
