### ISSUE TITLE
Invite discussion and examples of lesson project management from Incubator Developers

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#137]
In the first pilot, there was demonstrated demand for insight from lesson developers about how they manage issues in their repositories and how they manage their lesson projects/repositories as a whole.

We could invite Incubator Developers to share their approaches in blog posts, and/or as "testimonial" quotes in the curriculum, similar to the quote we are already using from Allegra.

**Comment by rcurty** [comment]
Our group at UCSB uses issues and labels and sets milestones in GitHub to organize our lesson development work. We also use a spreadsheet to track higher-level decisions, tasks, and assignees and record ideas and discussion points in our meeting notes before converting them into more detailed issues. We have been meeting regularly (weekly or biweekly) to maintain momentum, which helps us to make small but steady progress. We are currently working on a modularized version of the workshop that will allow instructors to choose what to teach based on the time, cohort needs, and learners’ entry knowledge. We would be happy to discuss our workflow further if you would like.

**Comment by tobyhodges** [comment]
Thanks so much for sharing these details, @rcurty. Your response chimes with my own experience, and it sounds like you have a very effective project management setup. I would like to quote your response in the Collaborative Lesson Development Training curriculum. Would you be ok with that?

**Comment by anenadic** [comment]
@svenvanderburg Would you be able to add a testimonial about the sprint you did in May on the [Intermediate RS skills course](https://github.com/carpentries-incubator/python-intermediate-development) that we could include in this lesson - what was the motivation behind it, what prompted you to do it, how you got about organising it, managing issues, what went well/not so well, and how the Incubator infrastructure made it easier for you to do it? Anything you may want to share, these are just some prompts.

**Comment by svenvanderburg** [comment]
@anenadic sure!

# Contributing to a lesson as outside collaborators
At the [Netherlands eScience Center](https://www.esciencecenter.nl/) we teach ['Intermediate Research Software Development'](https://carpentries-incubator.github.io/python-intermediate-development/) about 2/3 times per year. After every edition of the workshop we have a short meeting to distill the most important improvements we can make for the next time that we teach. We open op issues for improvements to the lesson material, such as https://github.com/carpentries-incubator/python-intermediate-development/issues/349 or https://github.com/carpentries-incubator/python-intermediate-development/issues/347. 

We are not direct maintainers of the lesson, but these issues are important for us to fix before teaching the next edition of the workshop, because we don't want to run into them again. Of course other users of the lesson would also benefit from the issues to be fixed.

Therefore, we organised a one-day sprint in which we, colleagues that are usually not working on the same team, together work on improving the lesson . By all working together on one day, together in the same room, we can have focus and get a lot done in a short amount of time, while not being distracted by the hundreds of other things we are all working on. Of course, we contacted the lesson maintainers to see if our efforts would be appreciated, see https://github.com/carpentries-incubator/python-intermediate-development/issues/343.

To organise our work we used a Microsoft Planner board where we keep track of what needs to happen
<img width="1178" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/9945255/7705b6a8-2387-4e00-a8b8-1eaa2a512260">

We bundled our contributions in [a fork of the carpentries incubator repo in our own Github organization](https://github.com/esciencecenter-digital-skills/python-intermediate-development). We created pull requests from our fork to a dedicated branch ([sprint-May2024](https://github.com/carpentries-incubator/python-intermediate-development/tree/sprint-May2024)) in the carpentries incubator repo. We reviewed each others work before a final review from the lesson maintainers.

In this way, we can: adapt the lesson to our own needs and contribute to the lesson in the Carpentries incubator in a smooth way that does not take away focus on other projectes of me and my colleagues.

I hope this helps you! Feel free to heavily edit this :)

**Comment by anenadic** [comment]
> @anenadic sure!
> 
> # Contributing to a lesson as outside collaborators
> At the [Netherlands eScience Center](https://www.esciencecenter.nl/) we teach ['Intermediate Research Software Development'](https://carpentries-incubator.github.io/python-intermediate-development/) about 2/3 times per year. After every edition of the workshop we have a short meeting to distill the most important improvements we can make for the next time that we teach. We open op issues for improvements to the lesson material, such as [carpentries-incubator/python-intermediate-development#349](https://github.com/carpentries-incubator/python-intermediate-development/issues/349) or [carpentries-incubator/python-intermediate-development#347](https://github.com/carpentries-incubator/python-intermediate-development/issues/347).
> 
> We are not direct maintainers of the lesson, but these issues are important for us to fix before teaching the next edition of the workshop, because we don't want to run into them again. Of course other users of the lesson would also benefit from the issues to be fixed.
> 
> Therefore, we organised a one-day sprint in which we, colleagues that are usually not working on the same team, together work on improving the lesson . By all working together on one day, together in the same room, we can have focus and get a lot done in a short amount of time, while not being distracted by the hundreds of other things we are all working on. Of course, we contacted the lesson maintainers to see if our efforts would be appreciated, see [carpentries-incubator/python-intermediate-development#343](https://github.com/carpentries-incubator/python-intermediate-development/issues/343).
> 
> To organise our work we used a Microsoft Planner board where we keep track of what needs to happen <img alt="image" width="1178" src="https://private-user-images.githubusercontent.com/9945255/333871916-7705b6a8-2387-4e00-a8b8-1eaa2a512260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODg3MDgsIm5iZiI6MTcxNjg4ODQwOCwicGF0aCI6Ii85OTQ1MjU1LzMzMzg3MTkxNi03NzA1YjZhOC0yMzg3LTRlMDAtYThiOC0xZWFhMmE1MTIyNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDkyNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTg0M2EzNTg0OTU0YTVlZWFkOGI3ODhmMjJkYzY1YjRhYjMzYTdmZTM5NDE1YjlkMjQ0MjNjMTViMDdjMzM3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j-MdiKvvSlTH33eGBoLDyPgk6l78qT36bEHvpsaJZkk">
> 
> We bundled our contributions in [a fork of the carpentries incubator repo in our own Github organization](https://github.com/esciencecenter-digital-skills/python-intermediate-development). We created pull requests from our fork to a dedicated branch ([sprint-May2024](https://github.com/carpentries-incubator/python-intermediate-development/tree/sprint-May2024)) in the carpentries incubator repo. We reviewed each others work before a final review from the lesson maintainers.
> 
> In this way, we can: adapt the lesson to our own needs and contribute to the lesson in the Carpentries incubator in a smooth way that does not take away focus on other projectes of me and my colleagues.
> 
> I hope this helps you! Feel free to heavily edit this :)

Many thanks @svenvanderburg! 🎉

**Comment by anenadic** [comment]
Add a testimonial box to directly quote Sven.

**Comment by anenadic** [comment]
> Our group at UCSB uses issues and labels and sets milestones in GitHub to organize our lesson development work. We also use a spreadsheet to track higher-level decisions, tasks, and assignees and record ideas and discussion points in our meeting notes before converting them into more detailed issues. We have been meeting regularly (weekly or biweekly) to maintain momentum, which helps us to make small but steady progress. We are currently working on a modularized version of the workshop that will allow instructors to choose what to teach based on the time, cohort needs, and learners’ entry knowledge. We would be happy to discuss our workflow further if you would like.

This is a great testimonial @rcurty - thank you. We would like to include it as a quote in the Collaborative Lesson Development Training curriculum with your permission - would you be ok with this?

**Comment by tobyhodges** [comment]
Reopening for a while longer in the hope we can quote Renata as well.

**Comment by rcurty** [comment]
@anenadic  and @tobyhodges, Apologies for missing your message earlier. Of course, please feel free to quote it!
