### ISSUE TITLE
Blooms taxonomy verbs for CS topics

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/lesson-development-training#221]
Some resources, as discussed in CLDT Trainer training: 

- https://ccecc.acm.org/files/publications/Blooms-for-Computing-20230119.pdf 
- http://www.ijiet.org/vol11/1504-AE004.pdf
- https://ccecc.acm.org/assessment/blooms-for-computing

**Comment by tobyhodges** [comment]
I really like the table starting on page 19 of https://ccecc.acm.org/files/publications/Blooms-for-Computing-20230807.pdf, which incorporates the computing verbs into the existing table of verbs in Bloom's. That could be a helpful resource to share with trainees in our curriculum.

To me, "collaborate" sits a little awkwardly in the table: the idea of collaboration as a creative act in itself (rather than as a _type_ of one of the other verbs) is not entirely convincing to me. However, its inclusion _does_ highlight the fact that collaboration is a skill (really a set of skills and concepts) that can and should be learned, alongside programming, debugging, etc, and I think that is a very positive outcome.

I would certainly be in favour of linking to the report when Bloom's is discussed in [_What Does An Objective Look Like?_](https://carpentries.github.io/lesson-development-training/05-objectives.html#what-does-an-objective-look-like)
