### ISSUE TITLE
List not rendering properly 

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#325]
In "Stay on Target" episode: https://carpentries.github.io/lesson-development-training/formative-assessment.html, the following list is not rendering properly (and I never figured out why and have tried different things to fix this).

<img width="1067" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/631719/d9353536-9ce7-4fcb-9be6-5248218f7689">

**Comment by tobyhodges** [comment]
The problem is we can make the list start from a different letter than _a_, but we cannot specify to skip a letter in the middle of an ordered list: i.e. we can make list items labelled `a.`, `b.`, `c.` etc, or `b.`, `c.`, `d.` etc, but **not** `a.`, `c.`, `d.`.

The easiest solution from our perspective is probably to adjust the order of the answer options such that `a.` or `d.` is the correct answer.
