### ISSUE TITLE
Clearer distinction between formative assessment and exercises?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#357]
### How could the content be improved?

In #347, @anenadic wrote:

> Wonder if we should call the episode "Designing exercises" (which is then followed by an episode "Implementing exercises") and then have reflection, concept maps and diagrams, checking in, think, pair, share all as "exercise types". And then the exercises in this bullet point list become "tasks" - setting challenges for learners to tackle and raising questions for discussion among the group. And then Parsons problems, fill-in-the blanks, etc. are all either separate "exercise types" or can fall under "tasks". In a way, formative assessment == exercise, which I am also not sure if I like 100%. 

@sstevens2 responded:

> I was thinking something similar but I wasn't sure how to articulate it or if I just didn't know enough of the pedagogy. I think of them all as exercises and formative assessment interchangeably. I guess think-pair-share could be any other type of exercise too in a way - MCQ, discussion, parson's problem. It seems like they are kind separated by the types that are coding vs non-coding. In fact, we use them that way in the exercise, I believe.

Let's use this issue as a place for further discussion

### Which part of the content does your suggestion apply to?

episodes/exercises.md and episodes/formative-assessment.md

**Comment by anenadic** [comment]
It does feel a bit that we are renaming the standard pedagogy terminology in order to make things clearer (for us and learners). But then Greg Wilson alway said "do not be afraid to sacrifice the truth for clarity" :-). And I agree with @sstevens2 think-pair-share is more a methodology than an exercise type (if that is what Sarah's is saying 😊) - e.g. it is a type of discussion. 

Maybe we can just have to agree that we cannot classify them in "clean" categories but could perhaps emphasise that we have coding and non-coding exercise types (and some that can be applied to both) - which we then actually follow up by an exercise for people working on lessons involving and not involving coding. My brain is fried now, will come back to this later 🤯 .

**Comment by anenadic** [comment]
Here is a related PR https://github.com/carpentries/lesson-development-training/pull/363 with some suggestions that we can comment on or decide to scrap altogether.

**Comment by anenadic** [comment]
Closed via PR https://github.com/carpentries/lesson-development-training/pull/363.
