### ISSUE TITLE
Lesson Design notes template additions

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#430]
### How could the content be improved?

The Lesson Design notes template Needs sections for the glossary and the key points and questions. Maybe we should consider a table for matching keypoints and questions together?

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/lesson-development-training/instructor/explanation.html

**Comment by tobyhodges** [comment]
I have added the following to [the Lesson Design Notes template (currently lines 83-102)](https://codimd.carpentries.org/HPwUE3FnTeSQJ9-_5EfU7Q?edit):

```markdown
## Glossary of terms
FIXME add a list of terms or jargon from your lesson, along with their definitions.
The syntax below will make your glossary render nicely when added to the `learners/reference.md` page of your lesson.

Term 1
: Definition 1
  add more lines here
  if you need to
  but indent them 
  by two spaces
  each time

Term 2
: Definition 2
  and so on...


## Completing lesson metadata
FIXME add questions and key points that summarise the most important messages of your episodes below. 
We typically aim to write the key points as answers to the questions.
```

Note that I did not include a table for the questions and key points. I decided against this because the Markdown table editor in CodiMD is quite fiddly and it is easy to get yourself in a mess. (I speak from deep, painful experience.) I think it's best to keep things relatively simple for our training.

@sstevens2 and @anenadic please can you take a look and tell me what you think needs changing?

**Comment by anenadic** [comment]
If we wanted to address key points for completeness, below line 82 in the template we could perhaps have:
`### Episode Keypoints` section where we ask them to summarise the main points as a bullet point list rather than a table.

We could have something similar above for the episode questions, if we wanted to, to match all episode elements we mentione and teach.

I agree tables are fiddly. 

I am going to approve this and leave it to @tobyhodges to decide if he is going to add the above two sections as bullet point lists.

**Comment by tobyhodges** [comment]
Good idea @anenadic, thanks. I have updated that section to look like this:

```markdown
## Completing lesson metadata
FIXME add questions and key points that summarise the most important messages of your episodes below. 
We typically aim to write the key points as answers to the questions.
An episode typically answers 1-3 questions.

### Episode Title
#### Questions
* What is the answer to question 1?
* What is the answer to question 2?
* etc.

#### Key Points
* This is the answer to question 1.
* This is the answer to question 2.
* etc.
```
