### ISSUE TITLE
Add codetext examples for additional callout types

### ISSUE THREAD

**Issue by ndporter** [carpentries/lesson-development-training#457]
### How could the content be improved?

Some callout types (like `spoiler`) show examples, but the code to execute them is not displayed on the rendered training page the way it is for `challenge` (for example). All types should have both unexecuted code blocks and rendered code blocks to see both the technique and results.

### Which part of the content does your suggestion apply to?

https://github.com/carpentries/lesson-development-training/blob/main/episodes/lesson-content.md?plain=1

**Comment by tobyhodges** [comment]
I don't agree that the full source code should be included here for each example div: our aim is to teach the principle of fenced divs and then show examples so that learners can see how the different classes would appear in their lessons. However, it is true that these examples would be clearer if the keyword used for each class of div was made more obvious in the curriculum. I have opened #458 to address this and to mention the `caution` class.

**Comment by ndporter** [comment]
@tobyhodges I appreciate that. The main point was to make it easy to find the keywords, anyway.
